### ISSUE TITLE
Design fixes

### ISSUE THREAD

**Issue by kalilsn** [jeancochrane/jeancochrane.com#5]
- [x] Some breakpoints need a little love on the homepage:
    - 988-991px two of the Jean illustrations show up stacked vertically
    - 768-991px menu is placed a little strangely
- [x] In the menu, the `border-bottom` ends are kinda funky when rendered in Chrome
- [x] `lightcoral` on `white` or `#ededed` (in the footer) is very low contrast!
- [x] Consider adding a caption (with the url) to the images that are also have links
    - For the record, `alt` text is good/necessary, but `title` text (usually) doesn't get read by screen readers. So: always use `alt`, and if you want the mouseover hover text, use the `title` attribute in addition to `alt`
- [x] I forgot to mention this on the call, but there's a weird bug that I can't reliably reproduce, where sometimes the tiles on the homepage will be arranged strangely. I don't know what causes it (no console errors or anything obvious) and I only did it in Chrome. Might not be a big deal since it resolves itself when you resize the window, but here's a screenshot:
![staging jeancochrane com_](https://user-images.githubusercontent.com/473542/33810942-eb608c04-ddd9-11e7-98b4-d34ee6f04058.png)

**Comment by jeancochrane** [comment]
That last one is unfortunately a bug in Isotope :(
